[__config__]
oldver = ".nvchecker_old.json"
newver = ".nvchecker_new.json"
keyfile = ".nvchecker_keys.toml"

[abra]
source = "gitea"
gitea = "coop-cloud/abra"
host = "git.coopcloud.tech"
use_max_tag = true
# why did they do this ;w;
exclude_regex = "(10\\.0\\.[53210]|9\\.0\\.0|8\\.0\\.[01])"

[jabba]
source = "github"
github = "Jabba-Team/jabba"
use_latest_release = true

[openrocket-beta]
source = "github"
github = "openrocket/openrocket"
use_latest_release = true
include_prereleases = true

[packer-plugin-arm-image]
source = "github"
github = "solo-io/packer-plugin-arm-image"
use_latest_release = true

[protolint]
source = "github"
github = "yoheimuta/protolint"
use_latest_release = true

[savilerow]
source = "regex"
url = "https://www-users.york.ac.uk/peter.nightingale/savilerow//releases.html"
regex = "Download ([0-9]+\\.[0-9]+\\.[0-9]+) for Linux"

[zigup]
source = "github"
github = "marler8997/zigup"
use_latest_release = true

[deap]
source = "github"
github = "deap/DEAP"
use_max_tag = true

[rasaeroii]
source = "regex"
url = "https://rasaero.com/home.htm"
regex = "Version ([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)"

[lrcget]
source = "github"
github = "tranxuanthang/lrcget"
use_latest_release = true

[sigdigger-with-docs]
source = "archpkg"
archpkg = "sigdigger"
strip_release = false

[opentakserver]
source = "github"
github = "brian7704/OpenTAKServer"
use_latest_release = true

[macchanger-dynamicoui]
source = "archpkg"
archpkg = "macchanger"
